package util;

public enum TokenType {
	IDENTIFIER,
    NUMBER_INTEGER,
    NUMBER_FLOAT,
    REL_OPERATOR,
    MATH_OPERATOR,
    ASSIGNMENT_OPERATOR,
    LEFT_PAREN,
    RIGHT_PAREN,

    // reserved WORDS
    INTEGER_DATA_TYPE,
    FLOATING_DATA_TYPE,
    PRINT_STATEMENT,
    CONDITIONAL_IF_STATEMENT,
    ALTERNATIVE_ELSE_STATEMENT,
    LOOP_FOR_STATEMENT
}
