package util;

public enum TokenType {
	IDENTIFIER,
    NUMBER_INTEGER,
    NUMBER_FLOAT,
    REL_OPERATOR,
    MATH_OPERATOR,
    ASSIGNMENT,
    LEFT_PAREN,
    RIGHT_PAREN,

    // reserved words
    INTEGER_DATA_TYPE,
    FLOATING_DATA_TYPE,
    PRINT_STATEMENT,
    CONDITIONAL_IF_STATEMENT,
    ALTERNATIVE_ELSE_STATEMENT,
}
